In [1]:
#Introduction to NumPy

import numpy as np
import sys

In [2]:

list = [1,2,3,4,5,6]
array=np.array(list)
array


array([1, 2, 3, 4, 5, 6])

In [3]:
list_of_lists = [[1,2,3],
		[4,5,6],
		[7,8,9]]
np.array(list_of_lists)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.random.random((2,2))

array([[0.82631909, 0.47506833],
       [0.24507371, 0.31834681]])

In [6]:
np.arange(0,4)

array([0, 1, 2, 3])

In [7]:
np.arange(4)

array([0, 1, 2, 3])

In [8]:
np.arange(0,9,3)

array([0, 3, 6])

##### Array takes less memory than Python list

In [9]:
SIZE = 10000000
list = range(SIZE)
print(str(sys.getsizeof(1)*len(list)) + " bytes")

280000000 bytes


In [10]:
arr = np.arange(SIZE)
print(str(arr.size*arr.itemsize) + " bytes")

80000000 bytes


#### Array operations are faster than Python list  

In [11]:
%%time
# list operations
list1=range(SIZE)
list2=range(SIZE)
result = [(x+y) for x,y in zip(list1,list2)]

CPU times: user 696 ms, sys: 64.5 ms, total: 760 ms
Wall time: 759 ms


In [12]:
%%time
# array operations
arr1=np.arange(SIZE)
arr2=np.arange(SIZE)
result = arr1+arr2

CPU times: user 99.9 ms, sys: 55.3 ms, total: 155 ms
Wall time: 154 ms
